typography_spectrum: 0.84335
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5206750987563282
  lightness: 0.11504589323885739
  saturation: 0.19820953533053398
  rhythmicContrast: 0.675104928901419
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74452
analytics:
  google: null
  facebook: null
  twitter: null
name: TestingRJ
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Testing RJ
purpose: []
